PORTNAME=	setuptools_dso
PORTVERSION=	2.9
CATEGORIES=	devel
MASTER_SITES=	PYPI

MAINTAINER=	pat@patmaddox.com
COMMENT=	setuptools extension to build non-python shared libraries
WWW=		https://github.com/mdavidsaver/setuptools_dso

LICENSE=	BSD

USES=		python
USE_PYTHON=	autoplist concurrent distutils

.include <bsd.port.mk>
