PORTNAME=	mashumaro
PORTVERSION=	3.9
CATEGORIES=	devel python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	pat@patmaddox.com
COMMENT=	Fast and well tested serialization library on top of dataclasses
WWW=		https://github.com/dbt-labs/dbt-core

LICENSE=	APACHE20

USES=		python
USE_PYTHON=	autoplist concurrent distutils

.include <bsd.port.mk>
