#!/bin/sh
#
# Check that newly added MOVED lines are valid
#

common_functions="$(realpath "$(dirname "$0")")/common.sh"
if [ -r "${common_functions}" ]; then
	. "${common_functions}"
fi

moved_changed=$(jj diff --summary | awk '/^M/ {print $2}' | grep -E '^MOVED$')
if [ $? -eq 0 ] ; then
	tree=$(jj root)
	# check the last seven days
	lastdate=$(date -v-7d "+%Y-%m-%d")

	errors=$(PORTSDIR=${tree} Tools/scripts/MOVEDlint.awk -v lastdate="${lastdate}")
	if [ $? -ne 0 ] ; then
		pre_commit_error "MOVED contains errors.\n" \
			"                  Please apply the suggested changes:\n"
		error "${errors}"
		exit 1
	fi
fi
