PORTNAME=	tree-sitter-jinja2
PORTVERSION=	0.1.0a1
CATEGORIES=	devel
MASTER_SITES=	PYPI

MAINTAINER=	pat@patmaddox.com
COMMENT=	A Jinja2 grammar for tree-sitter
WWW=		https://github.com/dbt-labs/tree-sitter-jinja2

LICENSE=	APACHE20

USES=		python
USE_PYTHON=	autoplist concurrent distutils

.include <bsd.port.mk>
