PORTNAME=	hologram
PORTVERSION=	0.0.16
CATEGORIES=	devel python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	pat@patmaddox.com
COMMENT=	A library for automatically generating Draft 7 JSON Schemas from Python dataclasses
WWW=		https://github.com/fishtown-analytics/hologram

LICENSE=	APACHE20

USES=		python
USE_PYTHON=	autoplist concurrent distutils

.include <bsd.port.mk>
