PORTNAME=	tree_sitter
PORTVERSION=	0.20.1
CATEGORIES=	devel python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
MASTER_SITES=	PYPI
MAINTAINER=	pat@patmaddox.com
COMMENT=	Python bindings to the Tree-sitter parsing library
WWW=		https://github.com/tree-sitter/py-tree-sitter

LICENSE=	MIT

USES=		python
USE_PYTHON=	autoplist concurrent distutils

.include <bsd.port.mk>
