PORTNAME=	snowflake-connector
PORTVERSION=	3.1.0
CATEGORIES=	databases python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	snowflake-connector-python-${PORTVERSION}

MAINTAINER=	pat@patmaddox.com
COMMENT=	Snowflake Connector for Python
WWW=		https://github.com/snowflakedb/snowflake-connector-python

LICENSE=	APACHE20

USES=		python
USE_PYTHON=	autoplist concurrent distutils

.include <bsd.port.mk>
